hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

github_login:
    pattern: /login/check-github

login:
    path:   /connect/github

logout:
    path:   /logout

dashboard_hub_app:
    resource: "@DashboardHubAppBundle/Resources/config/routing.yml"
    prefix:   /
